version: "3.7"
services:
  tasker:
    image: strm/tasker
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      configuration: |
        logging:
            level:
                ROOT: WARN
                org.springframework.web: WARN
                sh.strm: DEBUG
        schedule:
            - every: 1 hours
              task: vt_ip_monitor
        tasks:
            docker:
                - name: vt_ip_monitor
                  image: python:3
                  script-strict: true
                  script:
                    - cd /app
                    - pip install -r requirements.txt
                    - python3 VT_IP_Monitor.py
                  volumes:
                    - /home/ultron/Documents/tmp/Projects/VT_IP_Monitor/src:/app
